version: 0.2

phases:
  install:
    commands:
      - echo Software install chesthunna...
  build:
    commands:
      - echo Code build chesthunna...
  post_build:
    commands:
      - echo Build complete ayyindi!
